### ISSUE TITLE
Twitch got redesigned, stuff broke.

### ISSUE THREAD

**Issue by Kezxo** [DandelionSprout/adfilt#46] opened 2019-10-04 11:41 UTC
## Describe the problem below this line as meticulously and detailed as possible:
Can't see anything on https://www.twitch.tv/directory/following/live

## Add screenshots below if needed:
![image](https://user-images.githubusercontent.com/4523551/66204685-ebfba380-e69a-11e9-831e-386dc8d2030c.png)

## Add a screenshot of the extension's logger:

![image](https://user-images.githubusercontent.com/4523551/66204872-747a4400-e69b-11e9-94c9-96a8b049f67f.png)

## Which adblocker(s) and version did you use when testing this?
- [x] uBlock Origin

Other(s):

Version(s):
1.22.4
## Which filterlists did you use? Failing to write this will result in instant report closing.
Twitch: Even More Pure Viewing Experience 

## Which browser(s) and version did you use?

Firefox 69.0.2 (64-bit)

## (Optional) Which OS and version did you use?
- [x] Windows 10

Other(s):

Version:

**Comment by DandelionSprout** [comment] 2019-10-04 11:47
I have some problems replicating the problem in a hurry, but I have some suspicions of what the cause(s) could be.

Does `twitch.tv#@#div[class^="tw-mg-"]:has(a[href$="/following/hosts"]) > div:nth-of-type(3)` help on the case? If not, I propose using the surprisingly little-known `</>` button in the logger that displays a filetree of blocked elements and the involved entries.

**Comment by DandelionSprout** [comment] 2019-10-04 12:03
Nevertheless, I've done my best attempt at a hotfix now. If it works (or not), feel free to give me a heads-up about it.

**Comment by Kezxo** [comment] 2019-10-04 13:17
I got your hotfix and it now shows the main content of that page. Thanks!
The sidebar to the left is still hidden though but that might be intentional? I can fix that with ``www.twitch.tv#@#.side-nav`` in my own filters if it is. I forget if I want that sidebar or not..

Thanks again.

**Comment by DandelionSprout** [comment] 2019-10-04 14:19
My intention was for the sidebar to only be hidden while one is not logged in, as the previous design didn't have a button to shrink the sidebar during such circumstances.

I'll look into whether that is still the case in an hour or so.

**Comment by DandelionSprout** [comment] 2019-10-05 01:13
With the *Live* and *Overview* pages seemingly fixed now, and the sidebar no longer in need of being hidden, I'll consider this to be a resolved case. Thanks for reporting it to me.

**Closed by DandelionSprout** 2019-10-05 01:13 UTC
Labels: Problem report
