### ISSUE TITLE
Actually Legitimate URL Shortener breaks Zoom's MFA

### ISSUE THREAD

**Issue by Elaborendum** [DandelionSprout/adfilt#665] opened 2022-10-17 23:48 UTC
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

When trying to log in while having MFA enabled, the error "Required request parameter 'from' for method parameter type String is not present (-1)" appears and blocks you from continuing.

### Add screenshots below if needed

![imagen](https://user-images.githubusercontent.com/71190696/196303671-a204f8df-3942-446d-82a4-12766a842c6f.png)

### Add a screenshot of the extension's logger

![imagen](https://user-images.githubusercontent.com/71190696/196303736-1a1fa575-b365-437f-b569-c1ee64b855fb.png)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.44.4

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

![imagen](https://user-images.githubusercontent.com/71190696/196303851-5c92672b-a854-45b7-a41f-d8e9f818025b.png)

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

105.0.3

### Which OS(s) did you use when testing this?

Windows 10

### OS version(s)

21H2

**Comment by DandelionSprout** [comment] 2022-10-18 01:59
Your detailed screenshots allowed me to figure out the cause pretty much instantly, and the problem has been fixed now. Thanks again.

**Closed** 2022-10-18 01:58 UTC
Labels: Problem report
