### ISSUE TITLE
[BUG] :// blocking everything in adguard home

### ISSUE THREAD

**Issue by jfhenriques** [DandelionSprout/adfilt#1062] opened 2024-10-04 23:29 UTC
## Which entry/entries are you submitting?
It seems this las commit https://github.com/DandelionSprout/adfilt/commit/349a67b69fb111242115b2fd4e60e488e13d1420
in line 10640 broke adguard home. This line :// block every website

## Which things do they block, hide, or unbreak?

![image](https://github.com/user-attachments/assets/cb0d83ce-8d70-4c5e-9b4d-2b75998067e6)

## Which adblocker(s) and version did you use when writing and testing the entries?

- [ ] uBlock Origin
- [ ] AdGuard (Paid desktop or Android version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdBlock (Firefox or Manifest V2)
- [x] AdGuard Home
- [ ] Blokada
- [ ] I Still Don't Care About Cookies (The extension)
- [ ] AdNauseam
- [ ] AdGuard Private DNS

Other(s):

Adblocker version(s): v0.107.50

**Comment by DandelionSprout** [comment] 2024-10-04 23:34
Oh. Shit. Give me 4min.

**Comment by jfhenriques** [comment] 2024-10-04 23:36
Sorry, didn't use the pproper template and open again here :) https://github.com/DandelionSprout/adfilt/issues/1063

**Comment by DandelionSprout** [comment] 2024-10-04 23:43
Wait, hold on. Any particular reason why you're using the list's raw-domains versions instead of the dedicated AdGuard Home version (https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt)?

I'll get it fixed in the "Hosts" version anyway, but it seems to me like a pretty bad idea to use the Hosts version in AGH.

**Comment by DandelionSprout** [comment] 2024-10-04 23:54
Wait, wrong folder. Give me another 2min.

**Closed** 2024-10-04 23:56 UTC
Labels: Problem report

**Comment by jfhenriques** [comment] 2024-10-04 23:58
> Wait, hold on. Any particular reason why you're using the list's raw-domains version instead of the dedicated AdGuard Home version (https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt)?
> 
> I'll get it fixed in the raw-domains version anyway, but it seems to me like a pretty bad idea to use the Hosts version in AGH.

That's a fair question. Probably I used the wrong file by distraction a long time ago and as it never gave me any issue I never noticed.

 I've updated to the proper adguard home file. thanks a lot

**Comment by iam-py-test** [comment] 2024-10-05 00:04
I am curious what the cause was. Was there an issue with the conversion script?
Thank you

**Comment by DandelionSprout** [comment] 2024-10-05 00:06
That is unfortunately correct. I had handled some issues with the Hosts file earlier tonight, as I discovered that it even discarded comment rows that had `://` in them, incl. the homepage link.

So I removed the discardings, and it resulted in this.

**Comment by iam-py-test** [comment] 2024-10-05 00:07
Ok, thanks.

**Comment by celenityy** [comment] 2024-10-05 01:02
@DandelionSprout I'm still seeing this issue from `Dandelion Sprout's and other adblocker lists' IPs`.

![image](https://github.com/user-attachments/assets/1abdbf33-ea5b-484c-9347-cceec8755499)

I forced a blocklist update so it *should* be on the latest version. Happy to provide any other details as necessary!

**Comment by DandelionSprout** [comment] 2024-10-05 01:05
I'm looking into it right now.
