### ISSUE TITLE
Submission for browse websites without logging in

### ISSUE THREAD

**Issue by jschenke488** [DandelionSprout/adfilt#772] opened 2023-02-06 15:22 UTC
On Hackster.io, there is a signup modal that appears which also prevents scrolling. There's probably a better way to write the first filter, but it works for me. Tested with uBlock Origin on LibreWolf.
```
! Annoying sign up popup on Hackster.io
hackster.io##body > div > div > div > div > div > div > div:has-text(/join the world/i):xpath(../../../../../..)
hackster.io##body:remove-class(no-scroll)
```

**Comment by DandelionSprout** [comment] 2023-02-06 21:04
The annoying popup seems to be Firefox-engine-exclusive indeed, and I'm unsure to which extent AdGuard has implemented uBO's `:remove-class` yet, so I landed on these two:
```
hackster.io#?#div[data-hacksternova-key=AuthDialog]:has-text(Join the world)
hackster.io##body.no-scroll:style(overflow: unset !important)
```
I'll add them after I've had some dinner.

**Comment by Nojuuu** [comment] 2023-02-06 21:10
If you try to press signup button in the navbar it doesn't work with those.

**Comment by DandelionSprout** [comment] 2023-02-06 21:12
Hmm, good point. I had only tested with the "Log in" button in the upper right, and not the "Sign up" button. I'll get back to this matter in some hours' time.

**Comment by Nojuuu** [comment] 2023-02-06 23:15
I couldn't come up with any scriptlets that wouldn't break it.

**Comment by Nojuuu** [comment] 2023-02-06 23:24
Unless it is somehow possible to remove click event listener only from specific element, then you could make it to go `https://www.hackster.io/users/sign_up` instead of opening the modal.

**Comment by Nojuuu** [comment] 2023-02-07 03:40
```adblock
hackster.io##[data-hacksternova-key="AuthDialog"]:style(display: none;)
hackster.io##body:has([style="visibility: hidden; position: absolute; width: 100%; top: -10000px; left: 0px; right: 0px; transition: visibility 0s linear 0.3s, opacity 0.3s linear 0s; opacity: 0;"] + [style="visibility: hidden; position: absolute; width: 100%; top: -10000px; left: 0px; right: 0px; transition: visibility 0s linear 0.3s, opacity 0.3s linear 0s; opacity: 0;"]) [data-hacksternova-key="AuthDialog"]:style(display: block !important;)
```

Maybe?

**Comment by DandelionSprout** [comment] 2023-02-07 04:03
Although I was able to identify the specific script that causes that prompt on each page load, blocking it also prevent all sections on the homepage below the "Topics" one to fail to load. So I'm stumped.

**Comment by Nojuuu** [comment] 2023-02-07 06:10
```adblock
hackster.io##[data-hacksternova-key="AuthDialog"] [data-nested-dialog]:style(visibility: collapse; background-color: rgba(0, 0, 0, 0.4) !important)
hackster.io##body:has([action="SigninDialog"]:active, [action="SigninDialog"]:focus) [data-hacksternova-key="AuthDialog"] [data-nested-dialog]:style(background-color:rgba(0, 0, 0, 0.5) !important)
hackster.io##[data-hacksternova-key="AuthDialog"] [data-nested-dialog]:matches-css(background-color: rgba(0, 0, 0, 0.5)):style(visibility: visible !important;)
hackster.io##body:style(overflow: auto !important;)
```

Does this work?

**Comment by jschenke488** [comment] 2023-02-07 15:43
Found a filter that doesn't block the popup when it's from the signup button. From my testing, when sign up is actually clicked, `#g-recaptcha-response` is instead `#g-recaptcha-response-x` where x is an integer.
```adblock
hackster.io#?#div[data-hacksternova-key=AuthDialog]:has-text(Join the world):has(#g-recaptcha-response)
```

**Comment by jschenke488** [comment] 2023-02-07 15:51
> I'm unsure to which extent AdGuard has implemented uBO's `:remove-class` yet

https://github.com/AdguardTeam/ExtendedCss/issues/153

**Comment by DandelionSprout** [comment] 2023-10-08 00:22
It seems that no consensus was reached on a permanently functioning fix after 8 months, so I figure I can just as well close this by now, unfortunately.

**Closed by DandelionSprout** 2023-10-08 00:22 UTC
Labels: Submission

**Comment by Nojuuu** [comment] 2023-10-08 00:36
I can't even reproduce it, maybe they changed it?
