### ISSUE TITLE
eng-tips.com shows 404 page if invoked with viewthread

### ISSUE THREAD

**Issue by wojnilowicz** [DandelionSprout/adfilt#700] opened 2022-11-27 11:47 UTC
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

Bellow link shows 404 error
https://www.eng-tips.com/viewthread.cfm?qid=330514
while following link not
https://www.eng-tips.com

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.45.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

 Actually Legitimate URL Shortener Tool

### Which browser(s) did you use when testing this?

Chromium for Linux (Manifest V2)

### Browser version(s)

107.0.5304.110

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Fedora 37

**Comment by DandelionSprout** [comment] 2022-11-27 21:14
Thanks to the provided info, it was pretty easy to conclude that it was caused by `(...)removeparam=qid(...)`, which I've fixed in version `27November2022v1`.

**Closed** 2022-11-27 21:13 UTC
Labels: Problem report
