### ISSUE TITLE
Legitimate URL Shortener breaks many Facebook pages (not profiles)

### ISSUE THREAD

**Issue by ctp9** [DandelionSprout/adfilt#473] opened 2022-01-31 04:04 UTC
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I'm not sure how to log or describe this - but Facebook pages (not profiles) get significantly broken. If you own a page and go to "Manage" your page - lots of elements simply no longer load with Legitimate URL Shortener activated.

Pages freeze and are unable to render the functions of the requested page. Refreshing does not fix it, but only disabling the Legitimate URL Shortener fixes all these issues.

To replicate all these issues - you need to have created your own Page, and then try to Manage / edit Settings, etc.

Facebook pages use detailed URL descriptions for editing pages, and I think there are many conflicts in the current rules that are too restrictive and break everything to do with Page management.

### Add a screenshot of the extension's logger

[uBlock_Origin_logger.txt](https://github.com/DandelionSprout/adfilt/files/7972864/uBlock_Origin_logger.txt)

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

uBlock Origin 1.40.8

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
AdGuard Base
EasyList
AdGuard Tracking Protection
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
Online Malicious URL Blocklist
Phishing URL Blocklist
PUP Domains Blocklist
Fanboy’s Annoyance
uBlock filters – Annoyances
Peter Lowe’s Ad and tracking server list
Actually Legitimate URL Shortener Tool
oisd full
Spam404

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

97.0b9

### Which OS(s) did you use when testing this?

(Other)

### OS version(s)

Windows 11 (21H2)
Version 10.0.22000 Build 22000.469

**Comment by DandelionSprout** [comment] 2022-01-31 07:21
I don't have a Facebook account of my own, so I'll assign this to @iam-py-test for the immediate time being.

**Comment by ctp9** [comment] 2022-02-01 06:20
Updated original post with logger text file attached.

Page management tools seemed to work better today - so I partially suspect Facebook servers themselves were acting up when I submitted this report yesterday. But do still take a look through the log please and see if you can find any issue(s) and/or if there's any room for improvement/optimization, etc.

I'll upload more logs in the coming days from various sections of Facebook where elements get broken.

**Comment by iam-py-test** [comment] 2022-02-01 11:28
@ctp9 please try the following filter in your My Filters tab: `@@||facebook.com^$removeparam=__s`

**Comment by ctp9** [comment] 2022-02-01 21:47
Testing - will report soon.

**Comment by Nojuuu** [comment] 2022-02-02 15:30
Could also be reason for some of the problems:
https://bugzilla.mozilla.org/show_bug.cgi?id=1735595
https://bugzilla.mozilla.org/show_bug.cgi?id=1752270

**Comment by iam-py-test** [comment] 2022-02-02 21:01
> Could also be reason for some of the problems: https://bugzilla.mozilla.org/show_bug.cgi?id=1735595 https://bugzilla.mozilla.org/show_bug.cgi?id=1752270

Hmm...
@ctp9 try installing uBlock Origin in a Chrom(ium) browser and add Legit URL, see if that is the issue
In the mean time, let me see if I can convince someone in my household who has a Facebook account to help me repro

**Comment by ctp9** [comment] 2022-02-02 21:19
> > Could also be reason for some of the problems:
https://bugzilla.mozilla.org/show_bug.cgi?id=1735595
https://bugzilla.mozilla.org/show_bug.cgi?id=1752270
> 
> Hmm... @ctp9 try installing uBlock Origin in a Chrom(ium) browser and add Legit URL, see if that is the issue In the mean time, let me see if I can convince someone in my household who has a Facebook account to help me repro

One of the responses on the Mozilla bug tracker:

"Chrome has the same issue, it's a Facebook problem."

**Comment by DandelionSprout** [comment] 2022-02-03 08:13
I can borrow my mom's Facebook account to do surface-level skim tests, but I'd need to set off an hour to do so.

**Comment by iam-py-test** [comment] 2022-02-03 15:09
@ctp9 did the filter `@@||facebook.com^$removeparam=__s` fix the issue?
As Facebook is very popular, I'd like to fix this

**Comment by ctp9** [comment] 2022-02-03 21:35
> @ctp9 did the filter `@@||facebook.com^$removeparam=__s` fix the issue? As Facebook is very popular, I'd like to fix this

I'm still testing but so far seems to be working better than when I first submitted my report. I am still, however, occasionally experiencing the Mozilla bugs reported earlier regarding image loading when administering my own Pages, which seems to be universal across Chrome and Firefox.

**Comment by ctp9** [comment] 2022-02-03 21:41
> I can borrow my mom's Facebook account to do surface-level skim tests, but I'd need to set off an hour to do so.

Please also check out the "Activity Log" in the settings section of Facebook. Some things get broken there also when expanding/collapsing section trees. The entire Activity Log section sometimes stops loading with Legitimate URL Shortener enabled.

**Comment by iam-py-test** [comment] 2022-02-03 22:49
If that filter seems to help, I'm going to add it for now

**Comment by S0dV** [comment] 2022-02-10 00:27
So, is this reproduceable?

**Comment by iam-py-test** [comment] 2022-02-10 00:32
> So, is this reproduceable?

Do you have a FaceBook account? I don't and neither does Imre, so reproing is hard

**Comment by S0dV** [comment] 2022-02-10 00:32
> Do you have a FaceBook account

yes

**Comment by iam-py-test** [comment] 2022-02-10 00:41
> so I created a fb page, and I haven't observed any issues

Probably the temp fix from https://github.com/DandelionSprout/adfilt/commit/6f22b1c686e0ffa23e77a0bc82beb5eb254b4888
Try adding ` @@||facebook.com^$removeparam=__s,badfilter` and retesting.

**Comment by S0dV** [comment] 2022-02-10 00:44
no issue spotted on my end

**Comment by iam-py-test** [comment] 2022-02-10 00:45
Even with that filter + clearing cache & cookies (and resign in)

**Comment by S0dV** [comment] 2022-02-10 01:02
I'll see if I can make some time available for more testing.

**Comment by DandelionSprout** [comment] 2022-02-10 01:09
I sadly can't help after all, because my mom's PC died some days ago (A missing CPU retention bracket led to fan mounting problems, in turn causing bent pins on the CPU socket), and they sure haven't had any haste in pursuing a new PC to put their SSD into.

**Comment by krystian3w** [comment] 2022-02-10 07:40
If the pins haven't flown off the processor or motherboard, you can try to straighten them out instead of throwing +90% of the computer away in the electro-junk.

I would consider if you can buy a used cpu or motherboard itself very cheaply (cheaper than some finished PC with 6th or newer generation Intel if parent don't like oldie AMD and AMD Ryzen).

**Comment by S0dV** [comment] 2022-02-12 05:14
I haven't reproduced

**Comment by ctp9** [comment] 2022-02-12 06:27
At the moment things are working good. It may have been the Facebook / Mozilla bugs that were described earlier after all...

https://bugzilla.mozilla.org/show_bug.cgi?id=1735595
https://bugzilla.mozilla.org/show_bug.cgi?id=1752270

**Comment by iam-py-test** [comment] 2022-03-02 22:20
If Facebook is still working well, I think I can close the issue

**Comment by ctp9** [comment] 2022-03-02 23:53
Wait - I'll test a few more times and we will close it with my final confirmation. Just been busy and didn't get to re-test since last time.

**Comment by DandelionSprout** [comment] 2022-03-30 12:32
Given there seemingly hasn't been any problems with this from any involved party for approx. 7 weeks by now, I think it's safe to declare this a closed case for now. Comments will remain open.

**Closed by DandelionSprout** 2022-03-30 12:32 UTC
Labels: Problem report, Account required (Help wanted)
