### ISSUE TITLE
Amazonaws.com completed blocked with last commit

### ISSUE THREAD

**Issue by AleksCee** [DandelionSprout/adfilt#805] opened 2023-03-16 18:14 UTC
Hello, Imuse AdGuard DNS https://adguard-dns.io/ in the cloud with this list (https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt)

since https://github.com/DandelionSprout/adfilt/commit/5a1029170aaa6604af723e24eb90218f67d95ed8 all Amazonaws.com Domains are blocked. Is this a error from this list or by adguard dns?

thanks, Alex

**Comment by DandelionSprout** [comment] 2023-03-16 18:15
It was a problem for an hour, but was supposed to have been fixed now after I was given a tip about it in #804.

**Comment by AleksCee** [comment] 2023-03-16 18:22
![EA52879F-C0B1-4E12-8058-012D7FD56691](https://user-images.githubusercontent.com/2960655/225716602-f889e040-e1ce-4c4a-8352-e734af47f0ff.jpeg)

this is now, I will try it tomorrow again. Meanwhile I have set a user defined execution for the domain.

**Comment by iam-py-test** [comment] 2023-03-16 21:20
This seems to have been fixed. Also a duplicate of https://github.com/DandelionSprout/adfilt/issues/804

**Closed by iam-py-test** 2023-03-16 21:20 UTC
