### ISSUE TITLE
Cannot log into Twitter without taking an action

### ISSUE THREAD

**Issue by Poopooracoocoo** [DandelionSprout/adfilt#788] opened 2023-02-21 18:44 UTC
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

I cannot log into Twitter without taking an action such as liking a tweet or following a user. This makes logging in to make a Tweet, for example, slightly more difficult (although the settings icon will let you login, surprisingly 🤔 twitter sucks)

This is because the large blue banner that says "Don't miss what's happening. People on Twitter are the first to know" is the only way to sign in without taking an action. 

This seems to be the issue:
`! Removes the bottom login sticky banner about logging in, in the April 2020-ish redesign 🔨
twitter.com,twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion#?##layers > div[class*=" "]:first-of-type:has(a[href="/i/f `

Thank you for your incredible work!

### Add screenshots below if needed

Without Dandelion Sprout's Annoyances List 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51363864/220429483-8ba1d236-69dd-4d33-9721-e1cbdc7beefd.png">

With Dandelion Sprout's Annoyances List 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51363864/220429666-34155808-f4b8-40d1-b17d-70bb7d4a34a0.png">

### Add a screenshot of the extension's logger

<img width="960" alt="image" src="https://user-images.githubusercontent.com/51363864/220429874-a52c9b4d-cb55-4fbd-8440-fa60e22f1489.png">

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.47.0

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://ads-for-open-source.readthedocs.io/en/latest/_static/lists/opensource-ads.txt: 9-0, 1h.19m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 37013-448, 12m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 65-0, 1h.19m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 395-26, 1h.19m
    https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 25-0, 1h.19m
    adguard-annoyance: 64273-5889, 1h.19m
    fanboy-annoyance: 82180-519, 1h.19m
    ublock-annoyances: 4798-4, 1h.19m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33540-172, 1h.19m
    ublock-badware: 4476-5, 1h.19m
    ublock-privacy: 323-0, 1h.19m
    ublock-abuse: 79-0, 1h.19m
    ublock-unbreak: 1919-4, 1h.19m
    easylist: 62267-322, 1h.19m
    easyprivacy: 30962-1183, 1h.19m
    urlhaus-1: 5952-0, 1h.19m
    ublock-quick-fixes: 309-3, 1h.19m

### Which browser(s) did you use when testing this?

Firefox

### Browser version(s)

110.0

### Which OS(s) did you use when testing this?

Windows 11

### OS version(s)

22H2

**Comment by iam-py-test** [comment] 2023-02-21 21:13
This is caused by DandelionSprout's annoyances list including "Browse websites without logging in", which is designed to remove login-related annoyances. In my opinion, this is by design (my problem with broad "annoyances" lists). Also, that entry is marked as problematic:
> 🔨 = This category's entries are know to also break intentional login boxes for that site. Such entries may not be transferred to "uBlock Filters - Annoyances".

**Comment by DandelionSprout** [comment] 2023-02-22 06:27
I suppose that with the increased scrutiny that'd be placed on that sublist ever since Annoyances List got included in AdGuard, I seem to have come up with a fix that seems to be better than I previously expected.

<details><summary>The buttons instead being shrunk and moved to the bottom left:</summary>

![image](https://user-images.githubusercontent.com/22780683/220540466-bccaef89-8ec0-4fad-94b9-a5027d009339.png)

</details>

**Closed** 2023-02-22 06:29 UTC
Labels: Problem report

**Comment by Poopooracoocoo** [comment] 2023-02-24 08:23
The patch seems to move the messages bar (when logged in) to the left and gets cut off. Very minor issue and I'm not inconvenienced.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51363864/221128849-fb388910-cdaf-4880-9a96-22f31828776c.png">
