### ISSUE TITLE
nilesoft.org Detecting AD Block in Dandelion Sprout's Ad Lists

### ISSUE THREAD

**Issue by AdishSagarawat** [DandelionSprout/adfilt#768] opened 2023-02-03 10:26 UTC
See !
![image](https://user-images.githubusercontent.com/69076256/216576447-600af348-1eaf-4e63-a976-16dfe2ad5411.png)

Lists I am using:

![image](https://user-images.githubusercontent.com/69076256/216576583-7dab5d74-fc70-464a-9481-297e96a3aaae.png)

**Comment by iam-py-test** [comment] 2023-02-03 12:55
This appears to be caused by AdGuard Mobile Ads.
Also, oddly, I can't reproduce the issue on the homepage (but I see it on `http[s]://nilesoft[.]org/docs`)

**Comment by iam-py-test** [comment] 2023-02-03 13:21
This issue has been fixed by uAssets. In the future, please report any issues which are reproducible on default settings to https://github.com/uBlockOrigin/uAssets

**Closed by iam-py-test** 2023-02-03 13:21 UTC

**Comment by DandelionSprout** [comment] 2023-02-03 16:30
While I know that reporting to uAssets can seem daunting the first few times, I know that they (along with AdGuard Filters) have essentially monopoly on handling "Adblock detected" stuff, so such reports would have to go to those places no matter what, except in the longshot case that it'd be caused **specifically** by Dandelion Sprout's Annoyances List or similar.
