### ISSUE TITLE
Facebook sponsored posts

### ISSUE THREAD

**Issue by peace2000** [DandelionSprout/adfilt#258] opened 2021-08-28 17:14 UTC
## Which things do they block, hide, or unbreak?
Sponsored posts in Facebook. Each language interface has different "tag" for sponsored posts, making it mandatory to hide them via regional lists, instead of the main Easylist.

![kuva](https://user-images.githubusercontent.com/17256841/131225529-7d89f14f-d132-4071-bf96-a152802bd558.png)

(Censored private information)

## Which of my lists are you submitting it to?

Nordic filters

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (for browsers)
- [ ] AdBlock
- [ ] Adblock Plus
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)

Other(s):

Adblocker version(s):
1.37.3b20

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.
Easylist (English)
Nordic filters

Filters:

`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Sponset])` Bokmål
`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Sponsa])` Nynorsk
`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Sponsoreret])` Dansk
`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Stuðlað])` Føroyskt
`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Kostað])` Íslenska
`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Sponsrad])` Svenska

I use this one in the Finnish list for Finnish sponsored posts:

`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=Sponsoroitu])`

**Comment by DandelionSprout** [comment] 2021-08-28 19:50
I think this should be re-delegated to uAssets, who in addition to being able to find a language-neutral fix somehow, probably have Facebook accounts, which I don't.

Moreover, Facebook is kind-of a global website.

**Comment by peace2000** [comment] 2021-08-28 20:26
I'm afraid there isn't a language neutral version that works properly (or at least with good performance).

This would be a language neutral version:

`facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[href^="/ads/about/"])`

But it doesn't work well, it will just hide posts that are visible on-screen, others won't be hid even though that rule would match them. That's because there are attribute changes. I recently faced the same phenomenon https://github.com/uBlockOrigin/uBlock-issues/issues/1686 and though that it's just a bug... :D

My rule syntax uses only one procedural, language neutral rule would need to be combined with another, experimental procedural: https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectwatch-attrarg

I btw once asked a Finnish list entry concerning Facebook ads to be added to the Easylist https://github.com/easylist/easylist/pull/5456 but ryanbr said that FInnish Easylist should handle it. After that I have taken a policy that If there's an international site that has a Finnish UI and it has Finnish ad elements, I'll add it to the Finnish list.

**Comment by peace2000** [comment] 2021-08-28 20:41
![kuva](https://user-images.githubusercontent.com/17256841/131230516-76378eec-0063-4aa6-94e5-b3c6a324706d.png)

Screenshot from FB's DOM tree... :D

**Comment by peace2000** [comment] 2021-08-28 20:49
> I think this should be re-delegated to uAssets,

Btw, why uAssets instead of Easylist?

**Comment by DandelionSprout** [comment] 2021-08-28 20:57
How about `facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[class*=" "] > span[class][dir] > span[id]:not([class] > span[class]:not([id]):first-of-type + a[aria-label]:last-of-type)`?

**Comment by peace2000** [comment] 2021-08-28 21:01
Unfortunately that rule matches to all posts, not just ad ones.

**Comment by DandelionSprout** [comment] 2021-08-28 21:03
In that case I'm not sure what to do, other than to ask uAssets and AdGuard Filters about this instead. Especially since Ryan must've lied to you about where the entry should go, as global websites should *always* be in English-language lists.

**Comment by peace2000** [comment] 2021-08-28 21:12
Well, I was told no in that occasion which I linked, so don't know other solutions than to add it to the Finnish list.

btw, here is DOM tree from non-sponsored post:

![kuva](https://user-images.githubusercontent.com/17256841/131231154-6a980140-5f21-489a-b0cb-10933eb5ac55.png)

**Comment by Yuki2718** [comment] 2021-08-29 02:43
uAssets members keep asking user to reference this: `https://old.reddit.com/r/uBlockOrigin/wiki/solutions`. But I found FP by `facebook.com##div[role="feed"] div > span > span > a > span:upward(div[role="feed"] > div:not([data-pagelet*="group" i]))` in 3p frame (FB widget) so replaced this with `facebook.com##[role=feed] div > span > span > a > span >:not(:has-text(/^[^A-z]$/)):upward(div[role=feed] > div)`, an another idea of RraaLL.

@krystian3w Can you check if JP version of @peace2000 's filter is `facebook.com#?#div[data-pagelet^=FeedUnit_]:-abp-has(div[role=article] div[style^=border-radius] span[dir=auto] a[aria-label=広告])`?

>  probably have Facebook accounts, which I don't.
> 

They, unlike any other social media I've tested, can somehow detect test accounts and is very quick to ban them.

**Comment by peace2000** [comment] 2021-08-29 07:29
@Yuki2718 I checked and that filter works for JP FB. For both "generic" JP and "kansai" dialect. They have a different switch the filter works for both of them.

![kuva](https://user-images.githubusercontent.com/17256841/131242352-d0cedc0f-9b61-4d48-b14b-f76bafac85d6.png)

**Comment by peace2000** [comment] 2021-08-29 07:35
I btw also use this one for ads that have appeared at the of right rail:

`facebook.com#?#div[data-pagelet=RightRail] > div:-abp-has( div h3 > span:-abp-contains(Sponsoroitu))` but currently that ad is not appearing, at least for me so I'm not sure if that filter is still relevant.

But the filter that I previously posted, is relevant for Sponsored posts that appear all the time.

**Comment by ryanbr** [comment] 2021-08-29 08:50
> In that case I'm not sure what to do, other than to ask uAssets and AdGuard Filters about this instead. Especially since Ryan must've lied to you about where the entry should go, as global websites should _always_ be in English-language lists.

Lied about what, when?

**Comment by Yuki2718** [comment] 2021-08-29 12:56
Does `facebook.com##div[data-pagelet^="FeedUnit_"] div[role="article"] div[style^="border-radius"] span[dir="auto"] > span[id]:watch-attr(href) > a[href^="/ads/about/"]:upward(div[data-pagelet^="FeedUnit_"])` work for uBO? AG doesn't support watch-attr but `:matches-attr` can be used to unite all the language-specific filters into one.

**Comment by krystian3w** [comment] 2021-08-29 15:16
@ryanbr you closed in the past PR @peace2000 where he added Finland/Norawy/Sweeden word.

**Comment by DandelionSprout** [comment] 2021-08-29 15:44
>Lied about what, when?
peace2000 claimed you told him that entries for Facebook with Finnish GUI had to be in the Finnish list.

**Comment by krystian3w** [comment] 2021-08-29 15:54
Also AdGuard use own PureJS filter to hide self-promo so no need create filter based on ExtendedCSS aka Procedural cosmetic filter.

**Comment by peace2000** [comment] 2021-08-29 17:15
> `facebook.com##div[data-pagelet^="FeedUnit_"] div[role="article"] div[style^="border-radius"] span[dir="auto"] > span[id]:watch-attr(href) > a[href^="/ads/about/"]:upward(div[data-pagelet^="FeedUnit_"])`

That rule has issues hiding some off-screen sponsored posts. Doesn't perform well. :(

**Comment by krystian3w** [comment] 2021-08-29 17:40
I'm more concerned about whether someone will update the filter 2 times a day as Facebook starts changing the post structure (e.g. adding a fake hidden date that only matches-css could distinguish).

**Comment by Yuki2718** [comment] 2021-08-30 09:23
[Off-topic] @krystian3w @peace2000 If you have time, can you check JP translation of `##a[aria-label="Advertiser link"]` and `##a[aria-label="Advertiser"]` ?

**Comment by DandelionSprout** [comment] 2021-08-30 13:45
For clarification: Is it still expected of me to have to log on to someone's Facebook timeline (Presumably that of my mom) and test all these entries?

Just need to make sure before I set off time to visit my parents for the sole purpose of doing that.

**Comment by krystian3w** [comment] 2021-08-30 23:50
> `##a[aria-label="Advertiser link"]` and `##a[aria-label="Advertiser"]` ?

where found? I on homepage I have only translated: `aria-label="Sponsored"` into `aria-label="広告"`. (`広告`)

**Comment by krystian3w** [comment] 2021-08-30 23:52
> Facebook timeline (Presumably that of my mom)

You try exclude any FP (hide good content post as paid ad "sponsored")?

**Comment by krystian3w** [comment] 2021-08-31 00:00
Also in regional dialect (<strong>ślōnskŏ gŏdka</strong>) is used `<span aria-label="Szpōnzorowane"></span>`

**Comment by Yuki2718** [comment] 2021-08-31 10:06
@krystian3w Thank you very much!

**Comment by krystian3w** [comment] 2021-08-31 11:28
Maybe due parent:

`A[Advertiser] > *  object a[Advertiser image link]`

**Comment by peace2000** [comment] 2021-08-31 20:44
@krystian3w I remember seeing an ad on Facebook's right upper rail but it's appearance seems to be random for me, I don't currently see it. The only thing I see at the moment, are sponsored posts in newsfeed...

What this rule `##a[aria-label="Advertiser link"]` (or it's language specific version) actually hides? If I recall correctly, it only hides a title of that right upper ad? Can you tell if this has changed?

I remember now that due to that shortcoming, I made this filter:

 > `#?#div[data-pagelet=RightRail] > div:-abp-has( div h3 > span:-abp-contains(Sponsoroitu))`

As it hid the whole thing.

**Comment by peace2000** [comment] 2021-08-31 20:47
> 
> 
> For clarification: Is it still expected of me to have to log on to someone's Facebook timeline (Presumably that of my mom) and test all these entries?
> 
> Just need to make sure before I set off time to visit my parents for the sole purpose of doing that.

It's always up to list maintainers what sites are supported, but personally I think that it's a pity if one of the most popular sites isn't covered by adblockers.

**Comment by DandelionSprout** [comment] 2021-08-31 21:24
How about it reporting it to uAssets, then?

**Comment by DandelionSprout** [comment] 2021-08-31 21:30
That being said, have anyone here tested this whole situation with uBlock Filters turned on? Would've been nice to know, before I'd have attempted to re-delegate this report to them.

**Comment by peace2000** [comment] 2021-09-01 05:42
> 
> 
> That being said, have anyone here tested this whole situation with uBlock Filters turned on? Would've been nice to know, before I'd have attempted to re-delegate this report to them.

Yes, they don't hide / block them. I also double-checked by updating those lists. But no, they don't currently do anything to them.

**Comment by krystian3w** [comment] 2021-09-01 07:25
> How about it reporting it to uAssets, then?

In mega thread but may anybody generate commit in tribe "copy-paste".

**Comment by Yuki2718** [comment] 2021-09-01 11:23
>  If I recall correctly, it only hides a title of that right upper ad? Can you tell if this has changed?
> 

Oh, then I guess it's not worth blocked much.

**Comment by peace2000** [comment] 2021-09-01 14:31
@DandelionSprout That sound's fine, it's always the best if an universal solution is found :)

@krystian3w IMO that topic is a thread, instead of an issue report... :D I would open a new one concerning non-english filters or universal filter.

**Comment by krystian3w** [comment] 2021-09-01 20:28
Enough is wizmak commit.

**Comment by Yuki2718** [comment] 2021-09-02 10:42
`facebook.com##div[data-pagelet="RightRail"] a[aria-labelledby][target="_blank"][tabindex="0"]` looks quite generic, but if it's really useful can be added to EL.

**Comment by krystian3w** [comment] 2021-09-02 12:15
Blank may  suggest 3 party object.

**Comment by peace2000** [comment] 2021-09-03 18:29
Now I finally got to see that Rightrail ad :D not gonna refresh the page so that I won't "lose" it :D :D

![kuva](https://user-images.githubusercontent.com/17256841/132043753-d2ad1b70-ac67-495f-bf92-081735d12136.png)

Rule `facebook.com##div[data-pagelet="RightRail"] a[aria-labelledby][target="_blank"][tabindex="0"]` only blocks it partially. It removes the ad stuff under "Sponsoroitu" (Sponsored) label, but not the Sponsored label itself.. The filter that was provided by ABP works but If one wants to make it more specific for safety reasons, here's a picture of that element:

![kuva](https://user-images.githubusercontent.com/17256841/132045514-1126333e-a7d6-4ec5-b9f2-aae19b674c1e.png)

(That's the element where a language specific `##a[aria-label="Mainostaja"]` (or `##a[aria-label="Advertiser"]`) is being used.

My language neutral version:
`facebook##div[data-pagelet="RightRail"] a[aria-label][aria-labelledby][rel="nofollow noopener"][role=link][target=_blank][tabindex="0"]`

"Sponsoroitu" (Sponsored) label:

![kuva](https://user-images.githubusercontent.com/17256841/132049524-b9532c8c-afbe-44d0-a210-337f52259fc6.png)

That can't be hid in reliably way without using procedurals as you'll have to target a div element that has no specifiers (other than random class names). If you target an element that's in a lower position, there will be a blank remnant space, and I don't consider it as a proper result... :D

The whole DOM tree for that freaking rightrail ad is just.. huge... :D

![kuva](https://user-images.githubusercontent.com/17256841/132044051-da659522-54fb-4954-af9a-c1d193a78d96.png)
![kuva](https://user-images.githubusercontent.com/17256841/132044115-8616ac25-ab8f-4c72-91f2-05936138d4dc.png)

Imo, the best language neutral version to hide the whole thing with one rule:
facebook##div[data-pagelet="RightRail"] > div:has(a[aria-label][aria-labelledby][rel="nofollow noopener"][role=link][target=_blank][tabindex="0"])

For the time being, as uBO nor Easylist have that rule, I'll going to use this with the Finnish list:

facebook#?#div[data-pagelet="RightRail"] > div:-abp-has(a[aria-label="Mainostaja"])

**Comment by DandelionSprout** [comment] 2021-09-03 19:48
I have now spent 40min browsing through my mom's Facebook timeline, and I somehow saw no sponsored posts at all despite scrolling 240 posts down.

So that leads to the following situation:
* Fixed in stock AdGuard installations.
* Fixed in stock ABP installations.
* I can't submit `facebook.com##div[data-pagelet="RightRail"] a[aria-labelledby][target="_blank"][tabindex="0"]` nor `facebook.com##div[data-pagelet=RightRail] a[aria-label][aria-labelledby][rel="nofollow noopener"][role=link][target=_blank][tabindex="0"]` to uAssets because I have failed to reproduce them.
* No one else seem willing to submit them to uAssets, from what I can see.

I'll actually have to be a bit harsh for this one time's sake, and declare this a closed and mostly-resolved case (Comments will remain open). The ball is now on the court of whoever who wish to forward their successful reproductions to https://github.com/uBlockOrigin/uAssets/issues/3367

**Closed by DandelionSprout** 2021-09-03 19:48 UTC
Labels: Submission

**Comment by peace2000** [comment] 2021-09-03 20:01
@DandelionSprout Very strange that you didn't see any sponsored posts. It seems that Facebook sometimes shows ads and sometimes not. I see sponsored posts all the time.

But yeah, I understand your position. This issue report was mostly about adding Nordic specific filters. I'll see if EL will accept my rule.
